--
-- PostgreSQL database dump
--

\restrict 0QIEvcgGwxir7bjsMIagxCK89Zc1W1DbgWFEukIX0eCr9h4p5xQetAJrap7fcWg

-- Dumped from database version 16.14 (Debian 16.14-1.pgdg13+1)
-- Dumped by pg_dump version 16.14 (Debian 16.14-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: about_us; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.about_us (
    about_id integer NOT NULL,
    about_desc text,
    about_heading text NOT NULL,
    about_short_desc text
);


--
-- Name: about_us_about_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.about_us ALTER COLUMN about_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.about_us_about_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admins (
    admin_id integer NOT NULL,
    admin_about text,
    admin_contact character varying(255),
    admin_country text,
    admin_email character varying(255) NOT NULL,
    admin_image text,
    admin_job character varying(255),
    admin_name character varying(255) NOT NULL,
    admin_pass character varying(255) NOT NULL
);


--
-- Name: admins_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admins ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admins_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bundle_product_relation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bundle_product_relation (
    rel_id integer NOT NULL,
    bundle_id integer,
    product_id integer,
    rel_title character varying(255) NOT NULL
);


--
-- Name: bundle_product_relation_rel_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bundle_product_relation ALTER COLUMN rel_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bundle_product_relation_rel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    id integer NOT NULL,
    ip_add character varying(255) NOT NULL,
    p_price character varying(255),
    p_id integer,
    qty integer,
    size text
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    cat_id integer NOT NULL,
    cat_image text,
    cat_title text NOT NULL,
    cat_top text
);


--
-- Name: categories_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_us; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_us (
    contact_id integer NOT NULL,
    contact_desc text,
    contact_email text,
    contact_heading text
);


--
-- Name: contact_us_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_us ALTER COLUMN contact_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_us_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.coupons (
    coupon_id integer NOT NULL,
    coupon_code character varying(255) NOT NULL,
    coupon_limit integer,
    coupon_price character varying(255) NOT NULL,
    coupon_title character varying(255) NOT NULL,
    coupon_used integer,
    product_id integer
);


--
-- Name: coupons_coupon_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.coupons ALTER COLUMN coupon_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_coupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customer_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer_orders (
    order_id integer NOT NULL,
    customer_id integer,
    due_amount double precision,
    invoice_no bigint,
    order_date timestamp(6) without time zone,
    order_status text,
    qty integer,
    size text,
    customer_address text,
    customer_name character varying(255),
    customer_phone character varying(255)
);


--
-- Name: customer_orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer_orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customers (
    customer_id integer NOT NULL,
    customer_address text,
    customer_city text,
    customer_confirm_code text,
    customer_contact character varying(255),
    customer_country text,
    customer_email character varying(255) NOT NULL,
    customer_image text,
    customer_ip character varying(255),
    customer_name character varying(255) NOT NULL,
    customer_pass character varying(255) NOT NULL
);


--
-- Name: customers_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enquiry_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enquiry_types (
    enquiry_id integer NOT NULL,
    enquiry_title character varying(255) NOT NULL
);


--
-- Name: enquiry_types_enquiry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.enquiry_types ALTER COLUMN enquiry_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enquiry_types_enquiry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: manufacturers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.manufacturers (
    manufacturer_id integer NOT NULL,
    manufacturer_image text,
    manufacturer_title text NOT NULL,
    manufacturer_top text
);


--
-- Name: manufacturers_manufacturer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.manufacturers ALTER COLUMN manufacturer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manufacturers_manufacturer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id integer NOT NULL,
    amount double precision,
    created_at timestamp(6) without time zone,
    currency character varying(255),
    md5 character varying(255),
    order_id bigint,
    status character varying(255),
    transaction_id character varying(255),
    khqr_payload character varying(2048),
    qr_expires_at timestamp(6) without time zone,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pending_orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pending_orders (
    order_id integer NOT NULL,
    customer_id integer,
    invoice_no bigint,
    order_status text,
    product_id integer,
    qty integer,
    size text,
    customer_address text,
    customer_name character varying(255),
    customer_phone character varying(255)
);


--
-- Name: pending_orders_order_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pending_orders ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pending_orders_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_categories (
    p_cat_id integer NOT NULL,
    p_cat_image text,
    p_cat_title text NOT NULL,
    p_cat_top text
);


--
-- Name: product_categories_p_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_categories ALTER COLUMN p_cat_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_categories_p_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    product_id integer NOT NULL,
    cat_id integer,
    date timestamp(6) without time zone,
    manufacturer_id integer,
    p_cat_id integer,
    product_desc text,
    product_features text,
    product_img text,
    product_keywords text,
    product_label text,
    product_price double precision,
    product_psp_price double precision,
    product_title text NOT NULL,
    product_url text,
    product_video text,
    status character varying(255)
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store (
    store_id integer NOT NULL,
    store_button character varying(255),
    store_desc text,
    store_image character varying(255),
    store_title character varying(255) NOT NULL,
    store_url character varying(255)
);


--
-- Name: store_store_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terms (
    term_id integer NOT NULL,
    term_desc text,
    term_link character varying(100),
    term_title character varying(100)
);


--
-- Name: terms_term_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terms ALTER COLUMN term_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_term_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlist (
    wishlist_id integer NOT NULL,
    customer_id integer,
    product_id integer
);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wishlist ALTER COLUMN wishlist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: about_us; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.about_us (about_id, about_desc, about_heading, about_short_desc) FROM stdin;
\.


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.admins (admin_id, admin_about, admin_contact, admin_country, admin_email, admin_image, admin_job, admin_name, admin_pass) FROM stdin;
1	Initial system administrator account	\N	Cambodia	tityamonymac@gmail.com	admin-default.png	System Administrator	Admin User	$2a$10$ftO3t51Jh/bZczYFdIiHe.ZLCFNy59v2VtHTdvRQVVnswJffZmLh.
2	Initial system administrator account	\N	Cambodia	lolo@gmail.com	admin-default.png	System Administrator	Lolo Admin	$2a$10$r2LaBhCHlmyT02/4CzE1Ke.OBn3EjgYrI4B6nugA1YKoDQvxQ1icu
3	Initial system administrator account	\N	Cambodia	admin@mail.com	admin-default.png	System Administrator	Default Admin	$2a$10$3Gm6ov3I8DC0i6Xk1wjJuuROKrmpMZLXJceywJG07INuEmQDkFYPm
\.


--
-- Data for Name: bundle_product_relation; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bundle_product_relation (rel_id, bundle_id, product_id, rel_title) FROM stdin;
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.cart_items (id, ip_add, p_price, p_id, qty, size) FROM stdin;
71	172.18.0.1	\N	8	1	\N
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.categories (cat_id, cat_image, cat_title, cat_top) FROM stdin;
2	categories/33a7b897-bc10-4efe-8620-b2cdef427763_Headphone1.jpg	HEADPHONE	yes
3	categories/d512bddf-bd85-423d-9473-d3205c0cb110_Watch.jpg	WATCH	yes
\.


--
-- Data for Name: contact_us; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.contact_us (contact_id, contact_desc, contact_email, contact_heading) FROM stdin;
\.


--
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.coupons (coupon_id, coupon_code, coupon_limit, coupon_price, coupon_title, coupon_used, product_id) FROM stdin;
\.


--
-- Data for Name: customer_orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customer_orders (order_id, customer_id, due_amount, invoice_no, order_date, order_status, qty, size, customer_address, customer_name, customer_phone) FROM stdin;
6	11	109	1172617413	2026-08-14 17:02:55.269155	Complete	1	M	\N	\N	\N
18	1	42	97813546	2026-08-15 02:57:48.912369	Complete	3	M	\N	\N	\N
19	1	41	1418219859	2026-08-15 03:00:03.402793	pending	1	M	\N	\N	\N
20	1	21	1104177765	2026-08-15 03:06:24.004945	pending	1	M	\N	\N	\N
21	7	21	1253353053	2026-08-15 17:44:54.661464	Complete	1	M	\N	\N	\N
22	11	107	272944010	2026-08-15 17:51:52.507737	pending	1	M	\N	\N	\N
23	11	21	1262134236	2026-08-15 18:37:29.323769	pending	1	M	\N	\N	\N
24	11	32	1505050251	2026-08-15 19:24:55.985847	pending	2	M	\N	\N	\N
25	11	42	663447604	2026-08-15 19:26:30.674556	pending	3	M	\N	\N	\N
26	11	32	1099088005	2026-08-15 19:26:42.31777	pending	2	M	\N	\N	\N
27	11	32	1904604965	2026-08-16 01:45:39.506641	pending	2	M	\N	\N	\N
28	\N	10	1205970181	2026-08-16 02:08:10.553617	pending	1	M	\N	\N	\N
29	\N	0	1485870656	2026-08-16 02:11:28.96591	pending	1	M	\N	\N	\N
30	\N	0	178418833	2026-08-16 02:11:49.914125	pending	1	M	\N	\N	\N
31	\N	0	1664343827	2026-08-16 02:22:48.984825	pending	1	M	\N	\N	\N
32	\N	10	575585727	2026-08-16 02:23:03.872389	pending	1	M	\N	\N	\N
33	\N	0	1081736821	2026-08-16 02:24:11.859925	pending	2	M	\N	\N	\N
34	\N	0	1304920731	2026-08-17 02:30:10.2532	pending	1	M	\N	\N	\N
35	\N	0	1817403578	2026-08-17 02:33:49.974214	pending	2	M	\N	\N	\N
36	\N	0	1613706183	2026-08-17 02:36:29.354357	pending	1	M	\N	\N	\N
37	\N	10	1358105698	2026-08-17 02:36:49.877181	pending	1	M	\N	\N	\N
38	\N	0	1175911380	2026-08-17 02:37:58.129465	pending	1	M	\N	\N	\N
39	\N	0	271242624	2026-08-17 02:49:08.213787	pending	2	M	\N	\N	\N
40	\N	0	400843127	2026-08-17 03:16:48.02598	pending	1	M	\N	\N	\N
41	\N	0	599044239	2026-08-17 03:17:21.798077	pending	1	M	\N	\N	\N
42	8	0	546050454	2026-08-17 07:43:08.052304	pending	1	M	\N	\N	\N
43	8	0.1	161662583	2026-08-17 08:04:29.732457	pending	1	M	\N	\N	\N
44	\N	0.01	936668336	2026-08-17 08:08:11.019556	pending	1	M	\N	\N	\N
1	7	108	172070843	2026-08-10 16:31:58.049518	Shipped	1	M	\N	\N	\N
46	\N	0.01	897312328	2026-08-17 16:29:51.293659	pending	1	M	\N	\N	\N
45	\N	0.01	1935451624	2026-08-17 16:02:43.292295	Complete	1	M	\N	\N	\N
47	\N	0.01	1773952842	2026-08-17 16:40:58.805558	Complete	1	M	\N	\N	\N
48	12	0.01	211829622	2026-08-18 02:53:22.526513	pending	1	M	\N	\N	\N
49	\N	0.02	968873000	2026-08-18 02:56:12.853579	pending	2	M	\N	\N	\N
51	1	0.01	1308573078	2026-08-18 16:41:59.418036	pending	1	M	\N	\N	\N
50	\N	0.05	558840036	2026-08-18 02:57:31.502358	Complete	1	M	\N	\N	\N
52	\N	0.01	1165535237	2026-08-18 17:28:34.822472	pending	1	M	\N	\N	\N
53	\N	0.01	1527002559	2026-08-18 17:31:32.285074	pending	1	M	\N	\N	\N
54	\N	0.02	202118494	2026-08-18 17:42:31.350102	pending	2	M	\N	\N	\N
55	\N	0.01	2204876	2026-08-19 02:36:35.030672	pending	1	M	\N	\N	\N
7	7	108	436504259	2026-08-14 17:13:55.364832	Delivered	1	M	\N	\N	\N
56	\N	0.01	482749746	2026-08-19 03:03:55.729042	pending	1	M	\N	\N	\N
57	\N	0.01	518041173	2026-08-19 03:05:15.836438	pending	1	M	\N	\N	\N
58	1	0.01	267769450	2026-08-27 06:21:36.966649	pending	1	M	Steung Meanchey	Test Customer	08856614665
59	1	0.05	1658542938	2026-08-27 06:22:53.642006	pending	1	M	KPT	Test Customer	977855335
62	\N	0.1	163897476	2026-09-06 07:24:26.827048	pending	1	M	test	Lolo Admin	122342
60	\N	0.06	582381117	2026-09-06 07:20:17.912548	Paid	1	M	Steung Meanchey	Lolo Admin	885661465
63	\N	0.01	49704703	2026-09-06 07:24:54.445001	Paid	1	M	test	Lolo Admin	4253452
61	\N	0.01	1957469553	2026-09-06 07:23:06.671623	Paid	1	M	Testing	Lolo Admin	764266927
64	\N	0.01	890928810	2026-09-06 07:32:40.2942	Paid	1	M	Kampong thom	Lolo Admin	324523
65	\N	0.01	1553986350	2026-09-06 07:37:57.796134	Paid	1	M	Tesing	Lolo Admin	0933452
66	11	0.01	1352153704	2026-09-06 08:00:57.329604	Paid	1	M	test	Mony	12333
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customers (customer_id, customer_address, customer_city, customer_confirm_code, customer_contact, customer_country, customer_email, customer_image, customer_ip, customer_name, customer_pass) FROM stdin;
1	Phnom Penh	Phnom Penh	\N	012345678	Cambodia	customer@mail.com	\N	\N	Test Customer	$2a$10$ypuQx4qftt3A2LIkTdZNGeFoOWrSChunyMD2PBTBEssMZGd/ONE32
6	Steung Meanchey II	Phnom Penh	\N	783346263	CAM	kiki@gmail.com	\N	\N	kiki	$2a$10$Z.ID2viQNxA2jVdvK3e2huip4pTrqhQE7OZLbwqqpDwHPng4bELGy
7	Steung Meanchey 	Phnom Penh	\N	0663663626	CAM	kaka@gmail.com	\N	\N	kaka	$2a$10$vYLfq.Wk7sYM/qKnCs/H5uKElY4KPSZrZqU4cY4Kp.l/gaVLkqAJ2
8	\N	\N	\N	\N	\N	tityamonymao@gmail.com	https://lh3.googleusercontent.com/a/ACg8ocI45fSQajzGBshn2UEaxnrHS_6LhHFEbvw9ONSRhx0iO25S6ss=s96-c	\N	Tityamony Mao	$2a$10$j8BNOgBt822yc.5fZtNcju2XoIVOWuNAyG8A6pRXYPa/DKiAgcEH.
9	\N	\N	\N	\N	\N	maotityamony23@mekong.edu.kh	https://lh3.googleusercontent.com/a/ACg8ocLWe4YZB7zkhe4xNaDKgw8gH7_c74j2MXgvUDdICUIRlN4PSZ4=s96-c	\N	Student Mao Tityamony	$2a$10$yC2zD3hMmaTq5celxnVRcO7NddlmTmkXRUBdREX5/QlEcJFlShy02
11	Steung Meanchey	Phnom Penh	\N	886553727	CAM	Mony@gmail.com	\N	\N	Mony	$2a$10$6fAQDJA1tIT02OffxCKxTuytKGSaqR/8YWni4SzjXdKg1a2SF0MeG
12	steung mean chey	Phnom Penh	\N	883553582	cambodia	jonh@gmail.com	\N	\N	jonh	$2a$10$OZR9dcHwzD.AO0R2gqVdce9LDJdoRrdbjiR5y3.6Xr7XAJZHAzz0K
\.


--
-- Data for Name: enquiry_types; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.enquiry_types (enquiry_id, enquiry_title) FROM stdin;
\.


--
-- Data for Name: manufacturers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.manufacturers (manufacturer_id, manufacturer_image, manufacturer_title, manufacturer_top) FROM stdin;
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.payments (id, amount, created_at, currency, md5, order_id, status, transaction_id, khqr_payload, qr_expires_at) FROM stdin;
1	108	2026-08-10 16:31:58.360574	USD	7522ca3525daf99057ebb6ff36e8683c	1	PENDING	TXN-E50E5B21	\N	\N
2	108	2026-08-10 16:31:58.360544	USD	7522ca3525daf99057ebb6ff36e8683c	1	PENDING	TXN-58F7F80F	\N	\N
29	10	2026-08-16 02:23:04.086889	USD	785a1820bceeda082a3d5288f98813e5	32	PENDING	TXN-148D3AD6	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh620601023299340013178684698411601131786847584116630455A7	2026-08-16 02:33:04.118781
4	109	2026-08-14 17:02:55.603241	USD	8a180f03ca404065aa9758963aa1ee6e	6	PENDING	TXN-D029116C	\N	\N
3	109	2026-08-14 17:02:55.605468	USD	8a180f03ca404065aa9758963aa1ee6e	6	PAID	TXN-3EF5A929	\N	\N
5	108	2026-08-14 17:13:55.472306	USD	85e05fcad9eb2851c5a266e68ba24ebb	7	PENDING	TXN-12D381BF	\N	\N
6	108	2026-08-14 17:13:55.484934	USD	85e05fcad9eb2851c5a266e68ba24ebb	7	PENDING	TXN-8BC631FA	\N	\N
28	10	2026-08-16 02:23:04.086889	USD	785a1820bceeda082a3d5288f98813e5	32	PENDING	TXN-D4455C87	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh620601023299340013178684698411601131786847584116630455A7	2026-08-16 02:33:04.118774
8	42	2026-08-15 02:57:49.081728	USD	a3466b183c71e9668feb77f70d674385	18	PENDING	TXN-88382218	\N	\N
7	42	2026-08-15 02:57:49.089563	USD	a3466b183c71e9668feb77f70d674385	18	PAID	TXN-2824A6A1	\N	\N
9	41	2026-08-15 03:00:03.565351	USD	508bcd23eeabf1b704f991758bfd8465	19	PENDING	TXN-26C91F75	\N	\N
10	41	2026-08-15 03:00:03.565351	USD	508bcd23eeabf1b704f991758bfd8465	19	PENDING	TXN-66051FE4	\N	\N
11	21	2026-08-15 03:06:24.242475	USD	ae3b1bd7036efb5d130c162cba0188bf	20	PENDING	TXN-9AEE1C5F	\N	\N
12	21	2026-08-15 03:06:24.259917	USD	ae3b1bd7036efb5d130c162cba0188bf	20	PENDING	TXN-76D44D66	\N	\N
14	21	2026-08-15 17:44:54.868007	USD	049a97361799752cc192c9368033b21a	21	PENDING	TXN-302924DD	\N	\N
13	21	2026-08-15 17:44:54.860358	USD	049a97361799752cc192c9368033b21a	21	PAID	TXN-DAC1B197	\N	\N
15	107	2026-08-15 17:51:52.736643	USD	d806937a6604da343cf3d4a746122c00	22	PENDING	TXN-7F5F82A5	\N	\N
16	107	2026-08-15 17:51:52.754352	USD	d806937a6604da343cf3d4a746122c00	22	PENDING	TXN-94093386	\N	\N
17	21	2026-08-15 18:37:29.424201	USD	8dfaa0a3569d59eab58af3484829e8d4	23	PENDING	TXN-DF5A3CA4	\N	\N
18	21	2026-08-15 18:37:29.445208	USD	8dfaa0a3569d59eab58af3484829e8d4	23	PENDING	TXN-B689406A	\N	\N
19	32	2026-08-15 19:24:56.278875	USD	e578c442fd52ac6c2e67d91711f6df5b	24	PENDING	TXN-225E3A73	\N	\N
20	32	2026-08-15 19:24:56.309254	USD	e578c442fd52ac6c2e67d91711f6df5b	24	PENDING	TXN-107105EF	\N	\N
21	42	2026-08-15 19:26:30.81191	USD	17de514429a6fb79f605f40a7ab28351	25	PENDING	TXN-98533D7A	\N	\N
22	42	2026-08-15 19:26:30.838773	USD	17de514429a6fb79f605f40a7ab28351	25	PENDING	TXN-4CADBC53	\N	\N
23	32	2026-08-15 19:26:42.476762	USD	22507fb4f2f999448f7a87e80a0dfee2	26	PENDING	TXN-8B0B7BA2	00020101021229040000520459995303840540532.005802KH5911Ecomercshop6010Phnom Penh62060102269934001317868221837630113178682278376363047862	2026-08-15 19:39:43.764302
25	32	2026-08-16 02:05:59.460171	USD	1ca8fc0bdc55b4c9bc68b542fbd4bf03	27	PENDING	TXN-B60BCF68	00020101021229220018tityamony_mao@bkrt520459995303840540532.005802KH5911Ecomercshop6010Phnom Penh62060102279934001317868459595110113178684655951163045D96	2026-08-16 02:15:59.512058
24	32	2026-08-16 02:05:59.460173	USD	1ca8fc0bdc55b4c9bc68b542fbd4bf03	27	PENDING	TXN-D74F4701	00020101021229220018tityamony_mao@bkrt520459995303840540532.005802KH5911Ecomercshop6010Phnom Penh62060102279934001317868459595110113178684655951163045D96	2026-08-16 02:15:59.511959
26	10	2026-08-16 02:08:10.703676	USD	02d9e7c8a46d452886c994c65182a664	28	PENDING	TXN-2C38BF4E	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh6206010228993400131786846090712011317868466907126304070A	2026-08-16 02:18:10.712508
27	10	2026-08-16 02:08:10.728687	USD	1ca4428c6df7f7581f1a27a56acb7650	28	PENDING	TXN-44C628D0	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh620601022899340013178684609073301131786846690733630481D5	2026-08-16 02:18:10.733857
31	10	2026-08-17 02:36:50.034794	USD	021bc9abd19c58b4e9bc70d99b5b94a6	37	PENDING	TXN-F843FC98	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh62060102379934001317869342100450113178693481004563043FC3	2026-08-17 02:46:50.046072
30	10	2026-08-17 02:36:50.026746	USD	021bc9abd19c58b4e9bc70d99b5b94a6	37	PENDING	TXN-C7CAF022	00020101021229220018tityamony_mao@bkrt520459995303840540510.005802KH5911Ecomercshop6010Phnom Penh62060102379934001317869342100450113178693481004563043FC3	2026-08-17 02:46:50.046139
32	0.1	2026-08-17 08:04:31.407024	USD	13d59abc03decae5cb6e3dffb9994136	43	PENDING	TXN-47CBB008	00020101021229220018tityamony_mao@bkrt52045999530384054040.105802KH5911Ecomercshop6010Phnom Penh6206010243993400131786953871421011317869544714216304B5F1	2026-08-17 08:14:31.422495
33	0.1	2026-08-17 08:04:31.42825	USD	15bcaaaeeb2061c76adb237720fac9f3	43	PENDING	TXN-C4A69C3D	00020101021229220018tityamony_mao@bkrt52045999530384054040.105802KH5911Ecomercshop6010Phnom Penh62060102439934001317869538714340113178695447143463047C94	2026-08-17 08:14:31.434712
34	0.01	2026-08-17 08:08:12.298901	USD	cbea2d005a086cf25b74980ba25a3f70	44	PENDING	TXN-C33148F4	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh620601024499340013178695409230501131786954692305630411E2	2026-08-17 08:18:12.306142
35	0.01	2026-08-17 08:08:12.318137	USD	62385e5afde8bebd7603fc027d99e11e	44	PENDING	TXN-BC7EA76A	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010244993400131786954092323011317869546923236304E1C0	2026-08-17 08:18:12.32413
37	0.01	2026-08-17 16:02:45.463745	USD	db713738386dcc7b0ba177da61fe316c	45	PAID	TXN-E9532A7A	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010245993400131786982565476011317869831654766304C244	2026-08-17 16:12:45.478067
39	0.01	2026-08-17 16:29:55.067178	USD	9eb14cbf42575909ae494533edbb906f	46	PENDING	TXN-4C6CD0CD	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102469934001317869848063920113178698540639263049F65	2026-08-17 16:50:06.392605
38	0.01	2026-08-17 16:29:55.068844	USD	ab6818954e7f48bc4a35ab4cf7647c32	46	PENDING	TXN-506A7B87	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010246993400131786984799551011317869853995516304DFC0	2026-08-17 16:49:59.551998
36	0.01	2026-08-17 16:02:45.448751	USD	db713738386dcc7b0ba177da61fe316c	45	PAID	TXN-59BC113B	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010245993400131786982565476011317869831654766304C244	2026-08-17 16:12:45.477673
40	0.01	2026-08-17 16:41:00.811522	USD	1498b278a49096346d16c56c3b45dffc	47	PENDING	TXN-0CA45459	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010247993400131786985466774011317869860667746304038C	2026-08-17 17:01:06.775984
41	0.01	2026-08-17 16:41:00.842226	USD	3f1cee07a640e2f04ea0adf4dc401266	47	PAID	TXN-AB07E96E	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102479934001317869848608470113178698546084763049FB3	2026-08-17 16:51:00.848491
42	0.01	2026-08-18 02:53:26.935726	USD	22042df6e15e2b95a9625d8c9294a45d	48	PENDING	TXN-62F8E7CE	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102489934001317870216070240113178702220702463040B17	2026-08-18 03:03:27.037926
43	0.01	2026-08-18 02:53:26.934983	USD	155494afb8d502d9aabaf398d4795e9c	48	PENDING	TXN-C9455192	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102489934001317870216070580113178702220705863049A8F	2026-08-18 03:03:27.084974
44	0.02	2026-08-18 02:56:14.580271	USD	b1c7ab7818e246c1a5cd335e7488d6b7	49	PENDING	TXN-74BF4CC7	00020101021229220018tityamony_mao@bkrt52045999530384054040.025802KH5911Ecomercshop6010Phnom Penh6206010249993400131787021774602011317870223746026304CC44	2026-08-18 03:06:14.603764
45	0.02	2026-08-18 02:56:14.610081	USD	79ee070d86c1d80085a359b350e0c109	49	PENDING	TXN-DCEF9B10	00020101021229220018tityamony_mao@bkrt52045999530384054040.025802KH5911Ecomercshop6010Phnom Penh62060102499934001317870217746200113178702237462063041221	2026-08-18 03:06:14.621145
46	0.05	2026-08-18 02:57:33.061753	USD	b19e20aadde460ae2c634542595ec938	50	PENDING	TXN-8EF4C30C	00020101021229220018tityamony_mao@bkrt52045999530384054040.055802KH5911Ecomercshop6010Phnom Penh6206010250993400131787021853065011317870224530656304D05C	2026-08-18 03:07:33.066046
49	0.01	2026-08-18 16:42:01.019133	USD	fb0e3cd73f944d2a8f7835a40affa0d7	51	PENDING	TXN-2279537A	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102519934001317870719230980113178707252309863041353	2026-08-18 17:02:03.099448
47	0.05	2026-08-18 02:57:33.075035	USD	fa62b3af0edd25b80bbd8b3494b50186	50	PAID	TXN-C9952638	00020101021229220018tityamony_mao@bkrt52045999530384054040.055802KH5911Ecomercshop6010Phnom Penh620601025099340013178702185308501131787022453085630406DF	2026-08-18 03:07:33.085614
48	0.01	2026-08-18 16:42:01.006122	USD	bfbdc2a6b0eeb7d8d5cd21731526cd82	51	PENDING	TXN-DD48FDEB	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102519934001317870738446750113178707444467563042DD8	2026-08-18 17:34:04.676235
50	0.01	2026-08-18 17:28:36.172705	USD	95c3826113a83bc2dc44d8b6be4c32e3	52	PENDING	TXN-88CE0519	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102529934001317870741161770113178707471617763042FE8	2026-08-18 17:38:36.178248
51	0.01	2026-08-18 17:28:36.181154	USD	1627e8357512f1ba3f46a315d4e5bd4c	52	PENDING	TXN-70ABDCEF	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh620601025299340013178707411618501131787074716185630446F3	2026-08-18 17:38:36.185603
52	0.01	2026-08-18 17:31:34.601421	USD	a4fe36e8506c127cb8b9abd044e7fe0a	53	PENDING	TXN-7B595FDB	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102539934001317870742946040113178707489460463041543	2026-08-18 17:41:34.604892
56	0.01	2026-08-19 02:36:36.551328	USD	5da1fdfbc542404a897a854755f483fb	55	PENDING	TXN-C863CCB2	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh620601025599340013178710760111401131787108201114630479B8	2026-08-19 02:56:41.116721
53	0.01	2026-08-18 17:31:34.60393	USD	d2b2072917e83a4a0ee24318bd7fd211	53	PENDING	TXN-F82E98E0	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010253993400131787074895753011317870754957536304F277	2026-08-18 17:51:35.753734
54	0.02	2026-08-18 17:42:33.165546	USD	ebd65bf59ac5e368561bc45b6fbdc173	54	PENDING	TXN-36E27BFD	00020101021229220018tityamony_mao@bkrt52045999530384054040.025802KH5911Ecomercshop6010Phnom Penh620601025499340013178707495316801131787075553168630417BD	2026-08-18 17:52:33.169996
55	0.02	2026-08-18 17:42:33.171076	USD	c093f827afd3495f9a4e0866d01d2c60	54	PENDING	TXN-07772512	00020101021229220018tityamony_mao@bkrt52045999530384054040.025802KH5911Ecomercshop6010Phnom Penh62060102549934001317870749531730113178707555317363043322	2026-08-18 17:52:33.173997
62	0.01	2026-08-27 06:21:38.807871	USD	802170014289023ca94136df7b2be792	58	PENDING	TXN-0132B5FB	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010258993400131787811698812011317878122988126304A1CD	2026-08-27 06:31:38.813165
57	0.01	2026-08-19 02:36:36.563605	USD	82cdff7aefcef96f1b2667050e01354d	55	PENDING	TXN-6144AC2E	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010255993400131787107887761011317871084877616304D0D3	2026-08-19 03:01:27.766089
58	0.01	2026-08-19 03:03:57.754296	USD	42dd43ff8c7a2fbb4af80a990208e8e5	56	PENDING	TXN-C49427AF	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010256993400131787108637792011317871092377926304A6B4	2026-08-19 03:13:57.797085
59	0.01	2026-08-19 03:03:57.770563	USD	42dd43ff8c7a2fbb4af80a990208e8e5	56	PENDING	TXN-820DFFD3	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010256993400131787108637792011317871092377926304A6B4	2026-08-19 03:13:57.796006
61	0.01	2026-08-19 03:05:18.321259	USD	a63df01535deeb4d5d06f83e3e9322b8	57	PENDING	TXN-56B1A5DE	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010257993400131787108718365011317871093183656304B98B	2026-08-19 03:15:18.369904
60	0.01	2026-08-19 03:05:18.321175	USD	64b48291ccb477738af1b0e740d1b164	57	PENDING	TXN-95D551E9	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102579934001317871087183640113178710931836463047E02	2026-08-19 03:15:18.36992
63	0.01	2026-08-27 06:21:38.819602	USD	2aeffebba84584418c6b26878da919e7	58	PENDING	TXN-E592C34A	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010258993400131787811698822011317878122988226304C030	2026-08-27 06:31:38.822785
64	0.05	2026-08-27 06:22:54.887281	USD	b0661e299399aeb7fde3f9d18c002b00	59	PENDING	TXN-3F33E3DD	00020101021229220018tityamony_mao@bkrt52045999530384054040.055802KH5911Ecomercshop6010Phnom Penh62060102599934001317878117748880113178781237488863049DCD	2026-08-27 06:32:54.889111
65	0.06	2026-09-06 07:20:20.152938	USD	fd81c4ab949c3eeab3797a0b8fcb7acb	60	PAID	TXN-1D7C2CB2	00020101021229220018tityamony_mao@bkrt52045999530384054040.065802KH5911Ecomercshop6010Phnom Penh6206010260993400131788679220169011317886798201696304DDCB	2026-09-06 07:30:20.170082
69	0.1	2026-09-06 07:24:28.353743	USD	57d74c005b0ae984b2dc1380220c9373	62	PENDING	TXN-3EE629C8	00020101021229220018tityamony_mao@bkrt52045999530384054040.105802KH5911Ecomercshop6010Phnom Penh62060102629934001317886794683580113178868006835863040A90	2026-09-06 07:34:28.358423
67	0.01	2026-09-06 07:23:07.915387	USD	98d95792986b7ff70859d940a0c02397	61	PENDING	TXN-7368599D	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102619934001317886793879210113178867998792163041C1B	2026-09-06 07:33:07.92196
70	0.1	2026-09-06 07:24:28.363925	USD	ce6d08a596dde75d4dbc6640276eef76	62	PENDING	TXN-92F6D1D5	00020101021229220018tityamony_mao@bkrt52045999530384054040.105802KH5911Ecomercshop6010Phnom Penh62060102629934001317886794683660113178868006836663048697	2026-09-06 07:34:28.36737
72	0.01	2026-09-06 07:24:56.038101	USD	358bcc989b74b07b89d9fa31244e5b78	63	PAID	TXN-73104C80	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010263993400131788679496041011317886800960416304DD3E	2026-09-06 07:34:56.041497
76	0.01	2026-09-06 07:37:59.626221	USD	132c5e43af51aa3efe36a776fe2c7149	65	PENDING	TXN-21C6CFEB	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102659934001317886809200260113178868152002663043D27	2026-09-06 07:58:40.027086
77	0.01	2026-09-06 08:00:58.959161	USD	1ded9b7dd8f812ce753043b45ce143b0	66	PENDING	TXN-5B32F26B	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102669934001317886816589860113178868225898663043421	2026-09-06 08:10:58.987317
66	0.06	2026-09-06 07:20:20.152929	USD	fd81c4ab949c3eeab3797a0b8fcb7acb	60	PAID	TXN-F3DBD15C	00020101021229220018tityamony_mao@bkrt52045999530384054040.065802KH5911Ecomercshop6010Phnom Penh6206010260993400131788679220169011317886798201696304DDCB	2026-09-06 07:30:20.170228
68	0.01	2026-09-06 07:23:07.923342	USD	30e1b73db2595e13aac47c45471f9d34	61	PAID	TXN-C0DBB5B0	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102619934001317886793879260113178867998792663046AE6	2026-09-06 07:33:07.926699
71	0.01	2026-09-06 07:24:56.034915	USD	1ee1468b40ce23a7dfbcda10ad97ba95	63	PAID	TXN-C4908E16	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh620601026399340013178867949603901131788680096039630462E1	2026-09-06 07:34:56.039671
73	0.01	2026-09-06 07:32:41.771363	USD	b409f1742a5d312745456fdf0058dfdf	64	PAID	TXN-E86BFF87	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010264993400131788679961783011317886805617836304B434	2026-09-06 07:42:41.783969
74	0.01	2026-09-06 07:32:41.774019	USD	b409f1742a5d312745456fdf0058dfdf	64	PAID	TXN-749488DF	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh6206010264993400131788679961783011317886805617836304B434	2026-09-06 07:42:41.783986
75	0.01	2026-09-06 07:37:59.619485	USD	8f87fdb205ebc216b32d5c4775625ce5	65	PAID	TXN-1483F300	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102659934001317886802796280113178868087962863045C2E	2026-09-06 07:47:59.629868
78	0.01	2026-09-06 08:00:58.982303	USD	b1ad4e6b2836f72ea743cd21fedaaaeb	66	PAID	TXN-D6F4CED6	00020101021229220018tityamony_mao@bkrt52045999530384054040.015802KH5911Ecomercshop6010Phnom Penh62060102669934001317886816589920113178868225899263043ACD	2026-09-06 08:10:58.993156
\.


--
-- Data for Name: pending_orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pending_orders (order_id, customer_id, invoice_no, order_status, product_id, qty, size, customer_address, customer_name, customer_phone) FROM stdin;
1	7	172070843	pending	1	1	M	\N	\N	\N
2	11	1172617413	Paid	3	1	M	\N	\N	\N
3	7	436504259	pending	4	1	M	\N	\N	\N
14	1	97813546	Paid	5	3	M	\N	\N	\N
15	1	1418219859	pending	2	1	M	\N	\N	\N
16	1	1104177765	pending	5	1	M	\N	\N	\N
17	7	1253353053	Paid	5	1	M	\N	\N	\N
18	11	272944010	pending	4	1	M	\N	\N	\N
19	11	1262134236	pending	5	1	M	\N	\N	\N
20	11	1505050251	pending	5	2	M	\N	\N	\N
21	11	663447604	pending	5	3	M	\N	\N	\N
22	11	1099088005	pending	5	2	M	\N	\N	\N
23	11	1904604965	pending	5	2	M	\N	\N	\N
24	\N	1205970181	pending	6	1	M	\N	\N	\N
25	\N	1485870656	pending	6	1	M	\N	\N	\N
26	\N	178418833	pending	6	1	M	\N	\N	\N
27	\N	1664343827	pending	6	1	M	\N	\N	\N
28	\N	575585727	pending	5	1	M	\N	\N	\N
29	\N	1081736821	pending	6	2	M	\N	\N	\N
30	\N	1304920731	pending	6	1	M	\N	\N	\N
31	\N	1817403578	pending	6	2	M	\N	\N	\N
32	\N	1613706183	pending	6	1	M	\N	\N	\N
33	\N	1358105698	pending	5	1	M	\N	\N	\N
34	\N	1175911380	pending	6	1	M	\N	\N	\N
35	\N	271242624	pending	6	2	M	\N	\N	\N
36	\N	400843127	pending	7	1	M	\N	\N	\N
37	\N	599044239	pending	7	1	M	\N	\N	\N
38	8	546050454	pending	7	1	M	\N	\N	\N
39	8	161662583	pending	7	1	M	\N	\N	\N
40	\N	936668336	pending	8	1	M	\N	\N	\N
42	\N	897312328	pending	8	1	M	\N	\N	\N
41	\N	1935451624	Paid	8	1	M	\N	\N	\N
43	\N	1773952842	Paid	8	1	M	\N	\N	\N
44	12	211829622	pending	8	1	M	\N	\N	\N
45	\N	968873000	pending	9	2	M	\N	\N	\N
47	1	1308573078	pending	8	1	M	\N	\N	\N
46	\N	558840036	Paid	9	1	M	\N	\N	\N
48	\N	1165535237	pending	8	1	M	\N	\N	\N
49	\N	1527002559	pending	6	1	M	\N	\N	\N
50	\N	202118494	pending	8	2	M	\N	\N	\N
51	\N	2204876	pending	8	1	M	\N	\N	\N
52	\N	482749746	pending	8	1	M	\N	\N	\N
53	\N	518041173	pending	6	1	M	\N	\N	\N
54	1	267769450	pending	8	1	M	Steung Meanchey	Test Customer	08856614665
55	1	1658542938	pending	9	1	M	KPT	Test Customer	977855335
58	\N	163897476	pending	7	1	M	test	Lolo Admin	122342
56	\N	582381117	Paid	9	1	M	Steung Meanchey	Lolo Admin	885661465
59	\N	49704703	Paid	6	1	M	test	Lolo Admin	4253452
57	\N	1957469553	Paid	8	1	M	Testing	Lolo Admin	764266927
60	\N	890928810	Paid	8	1	M	Kampong thom	Lolo Admin	324523
61	\N	1553986350	Paid	8	1	M	Tesing	Lolo Admin	0933452
62	11	1352153704	Paid	8	1	M	test	Mony	12333
\.


--
-- Data for Name: product_categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_categories (p_cat_id, p_cat_image, p_cat_title, p_cat_top) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (product_id, cat_id, date, manufacturer_id, p_cat_id, product_desc, product_features, product_img, product_keywords, product_label, product_price, product_psp_price, product_title, product_url, product_video, status) FROM stdin;
3	\N	2026-08-14 17:27:09.504561	\N	\N			products/a0ae6469-9e64-46d7-9dfb-a53acf0a7ff4_Headphone1.jpg		new	0	0	headphone		\N	active
2	\N	2026-08-14 17:27:27.38729	\N	\N			products/5236d68a-b75b-444d-a06d-7382e75ce02b_Watch.jpg		new	29	0	Watch		\N	active
1	\N	2026-08-14 17:27:41.856958	\N	\N			products/e819b5a2-ff3a-4a21-b2dc-c5f031ce6f03_Watch1.jpg		new	100	10	Watch		\N	active
5	\N	2026-08-19 03:01:27.26854	\N	\N			products/594c4dda-003e-486f-afd4-9427653745dc_Watch.jpg		new	10	1	Watch		\N	active
4	\N	2026-08-19 03:01:50.248286	\N	\N			products/8ba5241d-3388-496f-9bdc-3ea2b54198e9_Watch1.jpg		new	0.01	99	Watch		\N	active
9	3	2026-09-06 07:18:46.125188	\N	\N	test product		products/5cbaebb5-1252-42fc-a5a7-bd0dfe778aee_headphone.jpg	KEY	hot	0.05	0	Watch		\N	active
8	3	2026-09-06 07:19:05.53485	\N	\N	Testing 		products/17024ee5-e210-4e51-b5b4-29ecf7fd0846_JBL.jpg	KEY	new	0.01	0	JBL		\N	active
7	2	2026-09-06 07:19:22.543999	\N	\N	test product		products/62e0e063-59d1-43fc-8f82-276152530fd7_headphone.jpg	none	new	0.1	0	headphone		\N	active
6	1	2026-09-06 07:19:44.038754	\N	\N			products/4713cd96-174a-4eb4-9442-92ccc4c6e8c8_Headphone1.jpg		new	0.01	0	Headphone		\N	active
\.


--
-- Data for Name: store; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.store (store_id, store_button, store_desc, store_image, store_title, store_url) FROM stdin;
\.


--
-- Data for Name: terms; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.terms (term_id, term_desc, term_link, term_title) FROM stdin;
\.


--
-- Data for Name: wishlist; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.wishlist (wishlist_id, customer_id, product_id) FROM stdin;
2	7	2
3	11	1
4	7	4
5	7	3
7	12	7
8	12	7
9	12	7
10	12	7
\.


--
-- Name: about_us_about_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.about_us_about_id_seq', 1, false);


--
-- Name: admins_admin_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.admins_admin_id_seq', 3, true);


--
-- Name: bundle_product_relation_rel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bundle_product_relation_rel_id_seq', 1, false);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 71, true);


--
-- Name: categories_cat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_cat_id_seq', 3, true);


--
-- Name: contact_us_contact_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.contact_us_contact_id_seq', 1, false);


--
-- Name: coupons_coupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.coupons_coupon_id_seq', 1, false);


--
-- Name: customer_orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customer_orders_order_id_seq', 66, true);


--
-- Name: customers_customer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customers_customer_id_seq', 12, true);


--
-- Name: enquiry_types_enquiry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.enquiry_types_enquiry_id_seq', 1, false);


--
-- Name: manufacturers_manufacturer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.manufacturers_manufacturer_id_seq', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.payments_id_seq', 78, true);


--
-- Name: pending_orders_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pending_orders_order_id_seq', 62, true);


--
-- Name: product_categories_p_cat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_categories_p_cat_id_seq', 1, false);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_product_id_seq', 9, true);


--
-- Name: store_store_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.store_store_id_seq', 1, false);


--
-- Name: terms_term_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.terms_term_id_seq', 1, false);


--
-- Name: wishlist_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.wishlist_wishlist_id_seq', 10, true);


--
-- Name: about_us about_us_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.about_us
    ADD CONSTRAINT about_us_pkey PRIMARY KEY (about_id);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (admin_id);


--
-- Name: bundle_product_relation bundle_product_relation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bundle_product_relation
    ADD CONSTRAINT bundle_product_relation_pkey PRIMARY KEY (rel_id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (cat_id);


--
-- Name: contact_us contact_us_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_us
    ADD CONSTRAINT contact_us_pkey PRIMARY KEY (contact_id);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (coupon_id);


--
-- Name: customer_orders customer_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT customer_orders_pkey PRIMARY KEY (order_id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (customer_id);


--
-- Name: enquiry_types enquiry_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enquiry_types
    ADD CONSTRAINT enquiry_types_pkey PRIMARY KEY (enquiry_id);


--
-- Name: manufacturers manufacturers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.manufacturers
    ADD CONSTRAINT manufacturers_pkey PRIMARY KEY (manufacturer_id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: pending_orders pending_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_orders
    ADD CONSTRAINT pending_orders_pkey PRIMARY KEY (order_id);


--
-- Name: product_categories product_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_categories
    ADD CONSTRAINT product_categories_pkey PRIMARY KEY (p_cat_id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: store store_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pkey PRIMARY KEY (store_id);


--
-- Name: terms terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (term_id);


--
-- Name: customers uk47v7cerfyndk4lx4vcu64cxyl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT uk47v7cerfyndk4lx4vcu64cxyl UNIQUE (customer_email);


--
-- Name: admins ukeoomxwhv11jtwt1lqr3h1nf4h; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT ukeoomxwhv11jtwt1lqr3h1nf4h UNIQUE (admin_email);


--
-- Name: coupons ukf1u99ssbdsqass9ntq968codg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukf1u99ssbdsqass9ntq968codg UNIQUE (coupon_code);


--
-- Name: payments uklryndveuwa4k5qthti0pkmtlx; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uklryndveuwa4k5qthti0pkmtlx UNIQUE (transaction_id);


--
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (wishlist_id);


--
-- Name: pending_orders fkbp4gcu9keiovbcn8p25dtrm8d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_orders
    ADD CONSTRAINT fkbp4gcu9keiovbcn8p25dtrm8d FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: pending_orders fkhx1mh03may45racnq2iffxdnx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pending_orders
    ADD CONSTRAINT fkhx1mh03may45racnq2iffxdnx FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id);


--
-- Name: customer_orders fkiwewyud8svmsotwucvm94aaw8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer_orders
    ADD CONSTRAINT fkiwewyud8svmsotwucvm94aaw8 FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 0QIEvcgGwxir7bjsMIagxCK89Zc1W1DbgWFEukIX0eCr9h4p5xQetAJrap7fcWg

