-- =========================================================
-- PostgreSQL schema for ecomerc_web
-- Cleaned and aligned with the Spring Boot JPA entities
-- =========================================================

DROP TABLE IF EXISTS wishlist CASCADE;
DROP TABLE IF EXISTS terms CASCADE;
DROP TABLE IF EXISTS store CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS pending_orders CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS manufacturers CASCADE;
DROP TABLE IF EXISTS enquiry_types CASCADE;
DROP TABLE IF EXISTS customer_orders CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS coupons CASCADE;
DROP TABLE IF EXISTS contact_us CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS bundle_product_relation CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS about_us CASCADE;

CREATE TABLE about_us (
    about_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    about_heading TEXT NOT NULL,
    about_short_desc TEXT,
    about_desc TEXT
);

INSERT INTO about_us (about_id, about_heading, about_short_desc, about_desc) VALUES
(1, 'About Us - Our Story',
 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
 'Rhone was the collective vision of a small group of weekday warriors.');

CREATE TABLE admins (
    admin_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_name VARCHAR(255) NOT NULL,
    admin_email VARCHAR(255) NOT NULL UNIQUE,
    admin_pass VARCHAR(255) NOT NULL,
    admin_image TEXT,
    admin_contact VARCHAR(255),
    admin_country TEXT,
    admin_job VARCHAR(255),
    admin_about TEXT
);

INSERT INTO admins (admin_id, admin_name, admin_email, admin_pass, admin_image, admin_contact, admin_country, admin_job, admin_about) VALUES
(1, 'Administrator', 'admin@mail.com', 'Password@123', 'user-profile-min.png', '7777775500', 'Morocco', 'Front-End Developer', 'Admin account for e-commerce management.');

CREATE TABLE bundle_product_relation (
    rel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rel_title VARCHAR(255) NOT NULL,
    product_id INTEGER NOT NULL,
    bundle_id INTEGER NOT NULL
);

CREATE TABLE cart_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_id INTEGER,
    ip_add VARCHAR(255) NOT NULL,
    qty INTEGER,
    p_price VARCHAR(255),
    size TEXT
);

CREATE TABLE categories (
    cat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cat_title TEXT NOT NULL,
    cat_top TEXT,
    cat_image TEXT
);

INSERT INTO categories (cat_id, cat_title, cat_top, cat_image) VALUES
(1, 'Feminine', 'no', 'feminelg.png'),
(2, 'Kids', 'no', 'kidslg.jpg'),
(3, 'Others', 'yes', 'othericon.png'),
(4, 'Men', 'yes', 'malelg.png');

CREATE TABLE contact_us (
    contact_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_email TEXT NOT NULL,
    contact_heading TEXT NOT NULL,
    contact_desc TEXT NOT NULL
);

INSERT INTO contact_us (contact_id, contact_email, contact_heading, contact_desc) VALUES
(1, 'ecomstore@mail.com', 'Contact To Us', 'If you have any questions, please feel free to contact us.');

CREATE TABLE coupons (
    coupon_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    coupon_title VARCHAR(255) NOT NULL,
    coupon_price VARCHAR(255) NOT NULL,
    coupon_code VARCHAR(255) NOT NULL UNIQUE,
    coupon_limit INTEGER NOT NULL,
    coupon_used INTEGER NOT NULL DEFAULT 0
);

INSERT INTO coupons (coupon_id, product_id, coupon_title, coupon_price, coupon_code, coupon_limit, coupon_used) VALUES
(1, 8, 'Sale', '10', 'CASTRO', 2, 1),
(2, 14, 'Sale', '65', 'CODEASTRO', 3, 1);

CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255) NOT NULL UNIQUE,
    customer_pass VARCHAR(255) NOT NULL,
    customer_country TEXT,
    customer_city TEXT,
    customer_contact VARCHAR(255),
    customer_address TEXT,
    customer_image TEXT,
    customer_ip VARCHAR(255),
    customer_confirm_code TEXT
);

INSERT INTO customers (customer_id, customer_name, customer_email, customer_pass, customer_country, customer_city, customer_contact, customer_address, customer_image, customer_ip, customer_confirm_code) VALUES
(1, 'user', 'user@ave.com', '123', 'United State', 'New York', '0092334566931', 'new york', 'user.jpg', '::1', ''),
(2, 'Demo Customer', 'demo@customer.com', 'Password123', 'DemoCountry', 'DemoCity', '700000000', 'DemoAddress', 'sample_image.jpg', '::1', ''),
(3, 'Thomas', 'thomas@demo.com', 'Password123', 'One Country', 'One City', '777777777', '111 Address', 'sample_img360.png', '::1', '1427053935');

CREATE TABLE customer_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(255),
    customer_address TEXT,
    due_amount DOUBLE PRECISION NOT NULL,
    invoice_no BIGINT,
    qty INTEGER,
    size TEXT,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_status TEXT
);

INSERT INTO customer_orders (order_id, customer_id, customer_name, customer_phone, customer_address, due_amount, invoice_no, qty, size, order_date, order_status) VALUES
(1, 1, 'user', '0092334566931', 'new york', 100.00, 1715523401, 2, 'Large', '2017-02-20 08:21:42', 'pending'),
(2, 2, 'Demo Customer', '700000000', 'DemoAddress', 20.00, 1762810884, 1, 'Medium', '2021-09-14 08:35:57', 'Complete');

CREATE TABLE enquiry_types (
    enquiry_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_title VARCHAR(255) NOT NULL
);

INSERT INTO enquiry_types (enquiry_id, enquiry_title) VALUES
(1, 'Order and Delivery Support'),
(2, 'Technical Support'),
(3, 'Price Concern');

CREATE TABLE manufacturers (
    manufacturer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_title TEXT NOT NULL,
    manufacturer_top TEXT,
    manufacturer_image TEXT
);

INSERT INTO manufacturers (manufacturer_id, manufacturer_title, manufacturer_top, manufacturer_image) VALUES
(1, 'Adidas', 'no', 'adilg.png'),
(2, 'Nike', 'no', 'niketransl.png'),
(3, 'Philip Plein', 'no', 'pplg.png'),
(4, 'Lacoste', 'no', 'lacostelg.png'),
(5, 'Polo', 'no', 'polobn.jpg'),
(6, 'Gildan 1800', 'no', 'sample_img360.png');

CREATE TABLE payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT,
    transaction_id VARCHAR(255) UNIQUE,
    md5 VARCHAR(255),
    khqr_payload TEXT,
    qr_expires_at TIMESTAMP,
    amount DOUBLE PRECISION,
    currency VARCHAR(10) DEFAULT 'USD',
    status VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pending_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(255),
    customer_address TEXT,
    invoice_no BIGINT,
    product_id INTEGER,
    qty INTEGER,
    size TEXT,
    order_status TEXT
);

INSERT INTO pending_orders (order_id, customer_id, customer_name, customer_phone, customer_address, invoice_no, product_id, qty, size, order_status) VALUES
(1, 1, 'user', '0092334566931', 'new york', 1715523401, 9, 2, 'Large', 'pending'),
(2, 2, 'Demo Customer', '700000000', 'DemoAddress', 1762810884, 12, 1, 'Medium', 'Complete');

CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_cat_id INTEGER,
    cat_id INTEGER,
    manufacturer_id INTEGER,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_title TEXT NOT NULL,
    product_url TEXT,
    product_img TEXT,
    product_price DOUBLE PRECISION,
    product_psp_price DOUBLE PRECISION,
    product_desc TEXT,
    product_features TEXT,
    product_video TEXT,
    product_keywords TEXT,
    product_label TEXT,
    status VARCHAR(255)
);

INSERT INTO products (product_id, p_cat_id, cat_id, manufacturer_id, date, product_title, product_url, product_img, product_price, product_psp_price, product_desc, product_features, product_video, product_keywords, product_label, status) VALUES
(1, 7, 4, 1, '2021-09-14 09:13:25', 'Denim Borg Lined Western Jacket', 'product-url-5', 'Next-Denim-Borg-Lined-Western-Jacket-0463-0064553-1-pdp_slider_l.jpg', 259.00, 100.00, 'Sample product description.', 'Sample features.', '<iframe width="854" height="480" src="https://www.youtube.com/embed/qRswlmADRa8" frameborder="0" allowfullscreen></iframe>', 'Jackets', 'Gift', 'product'),
(2, 5, 1, 2, '2021-09-14 17:06:30', 'Long Sleeves Polo Shirt for Men', 'product-url-9', 'product-1.jpg', 50.00, 35.00, 'Sample product description.', 'Sample features.', '<iframe width="854" height="480" src="https://www.youtube.com/embed/qRswlmADRa8" frameborder="0" allowfullscreen></iframe>', 'T-Shirt', 'Sale', 'product');

CREATE TABLE product_categories (
    p_cat_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_cat_title TEXT NOT NULL,
    p_cat_top TEXT,
    p_cat_image TEXT
);

INSERT INTO product_categories (p_cat_id, p_cat_title, p_cat_top, p_cat_image) VALUES
(1, 'Coats', 'no', 'coaticn.png'),
(2, 'T-Shirts', 'no', 'tshirticn.png'),
(3, 'Sweater', 'no', 'sweatericn.png'),
(4, 'jackets', 'yes', 'jacketicn.png'),
(5, 'Sneakers', 'yes', 'sneakericn.png'),
(6, 'Trousers', 'no', 'trousericn.png');

CREATE TABLE store (
    store_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_title VARCHAR(255) NOT NULL,
    store_image VARCHAR(255),
    store_desc TEXT,
    store_button VARCHAR(255),
    store_url VARCHAR(255)
);

INSERT INTO store (store_id, store_title, store_image, store_desc, store_button, store_url) VALUES
(1, 'London Store', 'store (3).jpg', '<p>180-182 RECENTS STREET, LONDON, W1B 5BT</p>', 'View Map', 'http://www.thedailylux.com/ecommerce'),
(2, 'New York Store', 'store (1).png', '<p>109 COLUMBUS CIRCLE, NEW YORK, NY10023</p>', 'View Map', 'http://www.thedailylux.com/ecommerce');

CREATE TABLE terms (
    term_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_title VARCHAR(100) NOT NULL,
    term_link VARCHAR(100) NOT NULL,
    term_desc TEXT NOT NULL
);

INSERT INTO terms (term_id, term_title, term_link, term_desc) VALUES
(1, 'Rules And Regulations', 'rules', 'Sample terms text for the platform.'),
(2, 'Refund Policy', 'link2', 'Sample refund policy text.');

CREATE TABLE wishlist (
    wishlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL
);

INSERT INTO wishlist (wishlist_id, customer_id, product_id) VALUES
(1, 1, 1),
(2, 2, 2);

-- =========================================================
-- End of schema
-- =========================================================
