services:
  - type: web
    name: ecomerc-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/products
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: KHQR_MERCHANT_ID
        sync: false
      - key: KHQR_MERCHANT_NAME
        value: Ecomerc Shop
      - key: KHQR_CITY
        value: Phnom Penh
      - key: KHQR_API_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  - type: web
    name: ecomerc-frontend
    runtime: static
    rootDir: Frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: VITE_GOOGLE_REDIRECT_URI
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
